### ISSUE TITLE
Support running without the --hf-token parameter and using ~/.cache/huggingface/token instead

### ISSUE THREAD

**Issue by ivanbaldo** [EricLBuehler/candle-vllm#31]
Sharing the model cache with Python's Huggingface Transformers including the `~/.cache/huggingface/token` file would be nice, it makes it a bit easier to run, and in some cases is a bit more flexible to have a file with the secret instead of an environment variable.

Currently running without the `--hf-token` parameter it crashes:

```rust
root@a07c64fd168b:~# RUST_BACKTRACE=full /root/.cargo/bin/candle-vllm --port 8080 llama7b --repeat-last-n 4096
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/openai/pipelines/llama.rs:93:52
stack backtrace:
   0:     0x55d28053b680 - std::backtrace_rs::backtrace::libunwind::trace::hc74d68e4e9860fea
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d28053b680 - std::backtrace_rs::backtrace::trace_unsynchronized::hf8e4c2f2a5bd29df
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d28053b680 - std::sys_common::backtrace::_print_fmt::h4f6fe0d2839f79bc
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55d28053b680 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd19378c79598340a
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d28059415f - core::fmt::rt::Argument::fmt::h59bd005c578b819c
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/core/src/fmt/rt.rs:138:9
   5:     0x55d28059415f - core::fmt::write::hc6d0fea41b7d9e9f
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/core/src/fmt/mod.rs:1094:21
   6:     0x55d28057ac09 - std::io::Write::write_fmt::haa7b0f41639b47d7
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/io/mod.rs:1714:15
   7:     0x55d28053b485 - std::sys_common::backtrace::_print::h5d490a94ac60fe6f
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55d28053b485 - std::sys_common::backtrace::print::hbaa9c19cd32d8c11
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55d280562b41 - std::panicking::default_hook::{{closure}}::h8910079f61b67bae
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:269:22
  10:     0x55d2805627df - std::panicking::default_hook::h7edb9fd7f54e7e29
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:288:9
  11:     0x55d280562fe9 - std::panicking::rust_panic_with_hook::h21aae3dc3ef5bbce
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:705:13
  12:     0x55d28053b921 - std::panicking::begin_panic_handler::{{closure}}::ha72f1c35114340ed
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:595:13
  13:     0x55d28053b756 - std::sys_common::backtrace::__rust_end_short_backtrace::h4b9d50b70e928d76
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55d280562d12 - rust_begin_unwind
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:593:5
  15:     0x55d27fd42e73 - core::panicking::panic_fmt::h1f248589eaa015cb
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:67:14
  16:     0x55d27fd42f03 - core::panicking::panic::ha7576b296f353a40
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:117:5
  17:     0x55d27fe64d05 - <candle_vllm::openai::pipelines::llama::LlamaLoader as candle_vllm::openai::pipelines::ModelLoader>::download_model::h35852d7688395361
  18:     0x55d27fdd2772 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h840672626d529183
  19:     0x55d27fdba6d5 - <core::pin::Pin<P> as core::future::future::Future>::poll::hada91331ad8af9c6
  20:     0x55d27fd6847e - tokio::runtime::scheduler::current_thread::Context::enter::hcadae44c6bd4a972
  21:     0x55d27fdba3fc - tokio::runtime::context::scoped::Scoped<T>::set::h8c46da17f5738f19
  22:     0x55d27fda2d8d - tokio::runtime::context::set_scheduler::h3ae1db3c76e6eddd
  23:     0x55d27fd68886 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h9087bc7e3b6248ad
  24:     0x55d27fd5acdd - tokio::runtime::context::runtime::enter_runtime::h83b56f50d8f9f15a
  25:     0x55d27fdc1ca4 - tokio::runtime::runtime::Runtime::block_on::h1be1cae2d7092a47
  26:     0x55d27fdeda2f - candle_vllm::main::h75bc07d9ebcc7535
  27:     0x55d27fd9fcef - std::sys_common::backtrace::__rust_begin_short_backtrace::hf956e45bfe2dcf62
  28:     0x55d27fd9fd22 - std::rt::lang_start::{{closure}}::hf05d036a2c013dd7
  29:     0x55d280554d97 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h04bbe96bde0bc897
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:284:13
  30:     0x55d280554d97 - std::panicking::try::do_call::he78cea8c5c5e38dc
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:500:40
  31:     0x55d280554d97 - std::panicking::try::h90115c76987a2911
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:464:19
  32:     0x55d280554d97 - std::panic::catch_unwind::hf9383826be3f5d9b
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  33:     0x55d280554d97 - std::rt::lang_start_internal::{{closure}}::h9558c46bab60ed0d
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:48
  34:     0x55d280554d97 - std::panicking::try::do_call::hc9c637fb9cb529b5
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:500:40
  35:     0x55d280554d97 - std::panicking::try::hdc72401b46fd9b08
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:464:19
  36:     0x55d280554d97 - std::panic::catch_unwind::hedb40674d8218c74
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  37:     0x55d280554d97 - std::rt::lang_start_internal::h4c2f75864f09731e
                               at /build/rustc-N04w3E/rustc-1.72.1+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:20
  38:     0x55d27fdeda95 - main
  39:     0x7f6377001d90 - <unknown>
  40:     0x7f6377001e40 - __libc_start_main
  41:     0x55d27fd4ec65 - _start
  42:                0x0 - <unknown>
```

**Comment by EricLBuehler** [comment]
@ivanbaldo this seems like a great idea. I just pushed a commit which adds this feature. Could you try it?

**Comment by EricLBuehler** [comment]
Is inference running? It should not work as PagedAttention is not implemented and everything is in flux.

**Comment by EricLBuehler** [comment]
It will work while it is doing the prompt.

**Comment by ivanbaldo** [comment]
I didn't test inference yet, since I have some other unrelated work to do first.
But since you are very helpful I decided to help you as much as I can and I am mixing both tasks hehe.
I can quickly launch an EC2 server with an Nvidia A10 24G VRAM that I use to run Podman containers with the CDI interface to access the GPU and run inference on it.
Been using that to run benchmarks of inferencers.
In the near future I am planning to benchmark on 2xA100 80G VRAM each to run Llama-2 70b without quantization and Mixtral 8x7b.
If by chance this project works in that setup then I can add it to the benchmarks, I am planning to do presentations of this.
Thanks!!!

**Comment by EricLBuehler** [comment]
Sounds exciting. Do you have a rough timeline in mind?

**Comment by ivanbaldo** [comment]
I hope to finish the benchmarks the 19th of February, but hoping to start benchmarking on the 2xA100 next week.

**Comment by ivanbaldo** [comment]
All the benchmarks are in this branch of this fork https://github.com/ivanbaldo/llama-inference/tree/ibaldoall .

**Comment by ivanbaldo** [comment]
It didn't work, this is the error:
```rust
3766.0 error[E0425]: cannot find value `var` in this scope
3766.0   --> src/openai/pipelines/mod.rs:75:51
3766.0    |
3766.0 75 |         (Some(envvar), None) => try_api!(env::var(var)),
3766.0    |                                                   ^^^ not found in this scope
3766.0    |
3766.0 help: consider importing one of these items
3766.0    |
3766.0 1  + use crate::openai::pipelines::env::var;
3766.0    |
3766.0 1  + use std::env::var;
3766.0    |
3766.0 
3766.0 error[E0433]: failed to resolve: use of undeclared crate or module `fs`
3766.0   --> src/openai/pipelines/mod.rs:76:40
3766.0    |
3766.0 76 |         (None, Some(path)) => try_api!(fs::read_to_string(path)),
3766.0    |                                        ^^ use of undeclared crate or module `fs`
3766.0    |
3766.0 help: consider importing one of these items
3766.0    |
3766.0 1  + use std::fs;
3766.0    |
3766.0 1  + use tokio::fs;
3766.0    |
3766.0 
3766.0 warning: unused imports: `env`, `fs`
3766.0  --> src/openai/pipelines/llama.rs:1:11
3766.0   |
3766.0 1 | use std::{env, fs, iter::zip, path::PathBuf, sync::Arc};
3766.0   |           ^^^  ^^
3766.0   |
3766.0   = note: `#[warn(unused_imports)]` on by default
3766.0 
3767.3 Some errors have detailed explanations: E0425, E0433.
3767.3 For more information about an error, try `rustc --explain E0425`.
3767.3 warning: `candle-vllm` (lib) generated 1 warning
3767.3 error: could not compile `candle-vllm` (lib) due to 2 previous errors; 1 warning emitted
```

**Comment by EricLBuehler** [comment]
I have pushed some changes since, could you try it again?

**Comment by ivanbaldo** [comment]
Now this:
```rust
error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /root/.cargo/git/checkouts/candle-lora-e71fb47097131b72/7fed136/candle-lora-transformers/src/varbuilder_utils.rs:98:23
    |
98  |         let tensors = candle_core::pickle::PthTensors::new(path)?;
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------ an argument of type `std::option::Option<&str>` is missing
    |
note: associated function defined here
   --> /root/.cargo/git/checkouts/candle-0c2b4fa9e5801351/b75e894/candle-core/src/pickle.rs:715:12
    |
715 |     pub fn new<P: AsRef<std::path::Path>>(path: P, key: Option<&str>) -> Result<Self> {
    |            ^^^
help: provide the argument
    |
98  |         let tensors = candle_core::pickle::PthTensors::new(path, /* std::option::Option<&str> */)?;
    |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `candle-lora-transformers` (lib) due to previous error
```

**Comment by EricLBuehler** [comment]
Very interesting. That API change from candle must have come out just in time to break your compilation. I just pushed a fix to candle-lora, could you try it again? It should compile now.

**Comment by ivanbaldo** [comment]
Hi, sorry Eric, had a busy morning!
It compiles although there are some warnings that you may like to get a look to:
```rust
warning: unused variable: `src_dev`
   --> src/backend/cache.rs:317:23
    |
317 |         (Device::Cuda(src_dev), Device::Cpu) => {
    |                       ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_src_dev`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `num_seqs`
  --> src/backend/paged_attention.rs:26:9
   |
26 |     let num_seqs = query.shape().dims()[0];
   |         ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_num_seqs`

warning: unused variable: `num_heads`
  --> src/backend/paged_attention.rs:27:9
   |
27 |     let num_heads = query.shape().dims()[1];
   |         ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_num_heads`

warning: unused variable: `max_num_blocks_per_seq`
  --> src/backend/paged_attention.rs:29:9
   |
29 |     let max_num_blocks_per_seq = block_tables.shape().dims()[1];
   |         ^^^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_max_num_blocks_per_seq`

warning: unused variable: `q_stride`
  --> src/backend/paged_attention.rs:30:9
   |
30 |     let q_stride = query.stride()[0];
   |         ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_q_stride`

warning: unused variable: `kv_block_stride`
  --> src/backend/paged_attention.rs:31:9
   |
31 |     let kv_block_stride = key_cache.stride()[0];
   |         ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_kv_block_stride`

warning: unused variable: `kv_head_stride`
  --> src/backend/paged_attention.rs:32:9
   |
32 |     let kv_head_stride = key_cache.stride()[1];
   |         ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_kv_head_stride`

warning: unused variable: `value_cache`
  --> src/backend/paged_attention.rs:15:5
   |
15 |     value_cache: Tensor,      // [num_blocks, num_heads, head_size, block_size]
   |     ^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_value_cache`

warning: unused variable: `num_key_value_heads`
  --> src/backend/paged_attention.rs:16:5
   |
16 |     num_key_value_heads: i32, // [num_heads]
   |     ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_num_key_value_heads`

warning: unused variable: `scale`
  --> src/backend/paged_attention.rs:17:5
   |
17 |     scale: f32,
   |     ^^^^^ help: if this is intentional, prefix it with an underscore: `_scale`

warning: unused variable: `context_lens`
  --> src/backend/paged_attention.rs:19:5
   |
19 |     context_lens: Tensor, // [num_seqs]
   |     ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_context_lens`

warning: unused variable: `max_context_len`
  --> src/backend/paged_attention.rs:21:5
   |
21 |     max_context_len: usize,
   |     ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_max_context_len`

warning: unused variable: `alibi_slopes`
  --> src/backend/paged_attention.rs:22:5
   |
22 |     alibi_slopes: Option<Tensor>,
   |     ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_alibi_slopes`

warning: unused variable: `dtype`
  --> src/backend/paged_attention.rs:23:5
   |
23 |     dtype: DType,
   |     ^^^^^ help: if this is intentional, prefix it with an underscore: `_dtype`

warning: unused variable: `is_fp8_e5m2_kv_cache`
  --> src/backend/paged_attention.rs:24:5
   |
24 |     is_fp8_e5m2_kv_cache: bool,
   |     ^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_is_fp8_e5m2_kv_cache`

warning: function `set_max_dynamic_shared_memory_size` is never used
 --> src/backend/paged_attention.rs:5:4
  |
5 | fn set_max_dynamic_shared_memory_size(_func: CudaFunction, _size: usize) {
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `candle-vllm` (lib) generated 16 warnings (run `cargo fix --lib -p candle-vllm` to apply 15 suggestions)
```

**Comment by EricLBuehler** [comment]
Great, this is as expected. Those warnings are due to the development state as I am waiting for coreylowman/cudarc#203, huggingface/candle#1467 and huggingface/candle#1412 to move forward.

**Comment by ivanbaldo** [comment]
Sorry but we should re-open the issue, since it doesn't seem to work (or maybe I am doing something wrong of course):

```bash
root@4be76ca848a1:/candle-vllm# /root/.cargo/bin/candle-vllm --port 8080 llama7b --repeat-last-n 4096
Error: APIError { data: "request error: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer.json: status code 401" }

root@4be76ca848a1:/candle-vllm# cat ~/.cache/huggingface/token 
hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by ivanbaldo** [comment]
Specifying the path works though:
```bash
root@4be76ca848a1:/candle-vllm# /root/.cargo/bin/candle-vllm --port 8080 --hf-token-path ~/.cache/huggingface/token llama7b --repeat-last-n 4096
```

**Comment by EricLBuehler** [comment]
Ok, this should be fixed now.

**Comment by ivanbaldo** [comment]
Strangely, it doesn't work still:
```bash
root@4be76ca848a1:/candle-vllm# /root/.cargo/bin/candle-vllm --port 8080 llama7b --repeat-last-n 4096
Error: APIError { data: "No such file or directory (os error 2)" }
```

**Comment by ivanbaldo** [comment]
It seems that it's sending to the kernel the following syscall which of course the kernel will not interpret, since the `~` is a shell feature:
`openat(AT_FDCWD, "~/.cache/huggingface/token", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`

**Comment by ivanbaldo** [comment]
BTW the `~/.cache` directory can be placed somewhere else, so the XDG mechanism should be followed to locate that directory, maybe Rust has a small and simple to use crate to do that lookup correctly and compliant with the XDG specification, maybe this one https://crates.io/crates/dirs .

**Comment by EricLBuehler** [comment]
I just pushed a commit which may fix this, could you try it again?

**Comment by ivanbaldo** [comment]
Failed with:
```rust
warning: unused import: `candle_core::cuda_backend::cudarc::driver::sys as cudarc_sys`
 --> src/backend/paged_attention.rs:3:5
  |
3 | use candle_core::cuda_backend::cudarc::driver::sys as cudarc_sys;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0277]: `std::option::Option<PathBuf>` doesn't implement `std::fmt::Display`
  --> src/openai/pipelines/mod.rs:79:13
   |
79 |             dirs::home_dir()
   |             ^^^^^^^^^^^^^^^^ `std::option::Option<PathBuf>` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `std::option::Option<PathBuf>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: this error originates in the macro `$crate::__export::format_args` which comes from the expansion of the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
warning: `candle-vllm` (lib) generated 1 warning
error: could not compile `candle-vllm` (lib) due to previous error; 1 warning emitted
```

**Comment by EricLBuehler** [comment]
Ok, the most recent commit should fix that.

**Comment by ivanbaldo** [comment]
Unfortunately not yet:
```rust
warning: unused import: `candle_core::cuda_backend::cudarc::driver::sys as cudarc_sys`
 --> src/backend/paged_attention.rs:3:5
  |
3 | use candle_core::cuda_backend::cudarc::driver::sys as cudarc_sys;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0308]: mismatched types
  --> src/openai/responses.rs:36:13
   |
36 |             Ok(v) => v,
   |             ^^^^^ expected `Option<PathBuf>`, found `Result<_, _>`
   |
  ::: src/openai/pipelines/mod.rs:79:22
   |
79 |             try_api!(dirs::home_dir())
   |             --------------------------
   |             |        |
   |             |        this expression has type `std::option::Option<PathBuf>`
   |             in this macro invocation
   |
   = note: expected enum `std::option::Option<PathBuf>`
              found enum `Result<_, _>`
   = note: this error originates in the macro `try_api` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
  --> src/openai/responses.rs:37:13
   |
37 |             Err(e) => {
   |             ^^^^^^ expected `Option<PathBuf>`, found `Result<_, _>`
   |
  ::: src/openai/pipelines/mod.rs:79:22
   |
79 |             try_api!(dirs::home_dir())
   |             --------------------------
   |             |        |
   |             |        this expression has type `std::option::Option<PathBuf>`
   |             in this macro invocation
   |
   = note: expected enum `std::option::Option<PathBuf>`
              found enum `Result<_, _>`
   = note: this error originates in the macro `try_api` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
warning: `candle-vllm` (lib) generated 1 warning
error: could not compile `candle-vllm` (lib) due to 2 previous errors; 1 warning emitted
```

**Comment by EricLBuehler** [comment]
Ah, my macro is not for Option. Mantually mapping in this push should fix it hopefully?

**Comment by ivanbaldo** [comment]
Nope, not yet, heheh:
```rust
error[E0599]: no method named `map_err` found for enum `std::option::Option` in the current scope
  --> src/openai/pipelines/mod.rs:79:30
   |
79 |             dirs::home_dir().map_err(APIError::from)?
   |                              ^^^^^^^ help: there is a method with a similar name: `map_or`

For more information about this error, try `rustc --explain E0599`.

```

**Comment by EricLBuehler** [comment]
Ok, this should fix it.

**Comment by ivanbaldo** [comment]
Ouch it seems that it needs to recompile some other stuff now, so it will take like 40m (candle-flash-attn takes ages here):
```rust
   Compiling candle-kernels v0.4.0 (https://github.com/huggingface/candle.git#e5eb9602)
   Compiling candle-flash-attn v0.4.0 (https://github.com/huggingface/candle.git#e5eb9602)
   Compiling candle-core v0.4.0 (https://github.com/huggingface/candle.git#e5eb9602)
   Compiling candle-examples v0.4.0 (https://github.com/huggingface/candle.git#e5eb9602)
   Compiling candle-nn v0.4.0 (https://github.com/huggingface/candle.git#e5eb9602)
   Compiling candle-lora v0.2.0 (https://github.com/EricLBuehler/candle-lora.git#232d8bda)
   Compiling candle-lora-macro v0.2.0 (https://github.com/EricLBuehler/candle-lora.git#232d8bda)
   Compiling candle-datasets v0.4.0 (https://github.com/huggingface/candle.git#e5eb9602)
   Compiling candle-sampling v0.2.0 (https://github.com/EricLBuehler/candle-sampling.git#b33fba39)
    Building [=======================> ] 508/516: candle-flash-attn(build), candle-core    
```

**Comment by EricLBuehler** [comment]
I tried to do that before, but the actions runner has no CUDA GPU. If you have any ideas that would be great, but if I will spin up another A10 soon to build.

**Comment by ivanbaldo** [comment]
But there's no need to have a GPU just to build, my laptop doesn't have a GPU actually.

**Comment by ivanbaldo** [comment]
On one hand, these tests could be handy and can easily added by commiting this file:
https://github.com/huggingface/candle/blob/main/.github/workflows/rust-ci.yml

And then maybe a job could be added similar to this:
```yaml
  test-build:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust Stable
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - uses: Swatinem/rust-cache@v2
      - run: apt-get update -y && apt-get install -y libssl-dev pkg-config
      - uses: Jimver/cuda-toolkit@v0.2.14
        id: cuda-toolkit
        with:
          cuda: '12.2.2'
      - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
      - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
      - run: CUDA_COMPUTE_CAP=86 /root/.cargo/bin/cargo build --features cuda,cudnn,flash-attn,nccl
```

**Comment by EricLBuehler** [comment]
I decided to not use that for now as when I tried it I had some trouble with building CUDA in the actions.

**Comment by ivanbaldo** [comment]
Maybe we can downgrade clap to 4.5.0?
To be able to use Rust from Ubuntu 22.04 instead of installing it directly from the web and having more moving parts (a good thing about distributions is having some things stable for some time).
```rust
error: failed to compile `candle-vllm v0.1.0 (/candle-vllm)`, intermediate artifacts can be found at `/candle-vllm/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  package `clap v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.1
  Either upgrade to rustc 1.74 or newer, or use
  cargo update -p clap@4.5.0 --precise ver
  where `ver` is the latest version of `clap` supporting rustc 1.72.1
```

**Comment by ivanbaldo** [comment]
Actually the 4.4.18 version of clap which supports Rust 1.70.0 according to this https://crates.io/crates/clap/4.4.18 .

**Comment by EricLBuehler** [comment]
If I'm not mistaken, we use 4.4.7 and candle uses 4.2.4. I cannot find 4.5.0 in candle or candle-vllm, so I don't think we use are specifying it? Could you try to downgrade on your machine?

**Comment by ivanbaldo** [comment]
Tried to downgrade already but couldn't.
Also removed Cargo.lock just in case but didn't work neither.
I don't know anything about Rust but my suspicion anyway, is that some dependency declares a hard dependency on that recent Clap and not candle-vllm directly...
Is there any method to diagnose this crates dependencies?

**Comment by EricLBuehler** [comment]
Yes, that is likely true. Are you running on a different machine, or did something change that is causing it to stop compiling now?

**Comment by ivanbaldo** [comment]
I always use containers and when encountering this problem I destroyed the container and started a new one, to avoid any pollution etc.
Don't worry about this, I will just `RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && ln -s /root/.cargo/bin/* /usr/local/bin` .
Compiling, results in an hour...

**Comment by EricLBuehler** [comment]
Ok, sorry that it takes so long!

**Comment by ivanbaldo** [comment]
Now it compiled correctly and got the token from the huggingface cache, excellent!!!
Thanks!

**Comment by EricLBuehler** [comment]
Great!
